# Default initial positions for Panda's ros2_control fake system

initial_joint_positions:
  panda_finger_joint1: 0
  panda_finger_joint2: 0
  panda_joint1: 0.0
  panda_joint2: -0.7853981633974483
  panda_joint3: 0.0
  panda_joint4: -2.356194490192345
  panda_joint5: 0.0
  panda_joint6: 1.5707963267948966
  panda_joint7: 0.7853981633974483

